//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(MVCModels.metadata.RoleMetaData))]
    
    public partial class Role
    {
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<byte> isactive { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<long> createdby { get; set; }
        public Nullable<System.DateTime> lastmodifiedon { get; set; }
    }
}
