//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

   // [MetadataType(typeof(CRM.MetaData.CalendarEventMetaData))]
    public partial class CalendarEvent
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> parenteventseq { get; set; }
        public string durationoption { get; set; }
        public Nullable<System.DateTime> durationuntill { get; set; }
        public Nullable<int> durationinminutes { get; set; }
        public Nullable<int> repeatedweekly { get; set; }
        public bool isrepeated { get; set; }
        public string eventtype { get; set; }
        public int deparmentid { get; set; }
    }
}
